# Generated by Django 5.2.6 on 2025-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('safety', models.CharField(blank=True, max_length=100)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'category'], name='ingredients_name_b61632_idx'), models.Index(fields=['safety'], name='ingredients_safety_635f46_idx')],
            },
        ),
    ]
