# Generated by Django 5.2.6 on 2025-10-03 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("EU", "European Union"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                        ],
                        default="US",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FormulaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dose_unit",
                    models.CharField(
                        choices=[
                            ("mg", "Milligrams"),
                            ("mcg", "Micrograms"),
                            ("g", "Grams"),
                            ("IU", "International Units"),
                        ],
                        default="mg",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ingredients.formula",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingredients.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "ingredient__name"],
            },
        ),
        migrations.AddIndex(
            model_name="formula",
            index=models.Index(
                fields=["owner", "-updated_at"], name="ingredients_owner_i_854fa9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formulaitem",
            unique_together={("formula", "ingredient")},
        ),
    ]
