# Generated by Django 5.2.6 on 2025-09-29 11:00

import main.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=main.storage_backends.MediaStorage(),
                upload_to="products/",
            ),
        ),
    ]
