# Generated by Django 5.2.6 on 2025-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="inquiry_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
