# Generated by Django 5.2.6 on 2025-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_contactmessage_inquiry_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
